name: swiftclean_admin
description: A new Flutter project.

# Prevent publishing to pub.dev
publish_to: 'none'

# Version
version: 1.0.0+1

# Environment SDK version
environment:
  # sdk: ^3.5.3
  sdk: ^3.7.2

# Project dependencies
dependencies:
  flutter:
    sdk: flutter

  # UI and design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # State management
  provider: ^6.1.2

  # Networking
  http: ^1.4.0

  # Local storage
  shared_preferences: ^2.2.2

  # Notifications
  fluttertoast: ^8.2.4

  # Navigation drawer
  flutter_slider_drawer: ^3.0.2
  standard_searchbar: ^2.1.1
  fl_chart: ^0.71.0
  syncfusion_flutter_charts: ^29.1.38
  flutter_bloc: ^9.1.1
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  flutter_rating_stars: ^1.1.0
  file_picker: ^10.1.9
  firebase_storage: ^12.4.10
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/image/
    - assets/icon/

  # Optional: Add custom fonts if needed
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
